Time
AntonStashevski/rack-interface pull request #1
Opened 2020-07-28 11:03 UTC by AntonStashevski

2020-07-28 19:40 UTC, BubuntuClu requested changes

2020-07-28 19:40 UTC, BubuntuClu commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
это все в гитигнор. не надо свои настройки пихать в общий репозиторий

2020-07-28 19:40 UTC, BubuntuClu commented on app.rb
> +  def call(env)
Rack приложение
Это данный класс. В его обязанности входит обработка запроса и формирование ответа в формате совместимом с rack. То есть здесь мы проверяем правильный ли пришёл URL или нужно отдать 404, хватает ли параметров или нужно отдать 400-й статус. При этом логику формирования тела ответа мы помещаем в отдельный класс бизнес логики.

Класс бизнес логики
Это отдельный простой Ruby класс, который может называться, например, TimeFormatter. Он ничего не должен знать о rack приложении, иными словами о том кто и где будет его использовать. Мы можем вызывать его из консоли или в другом Ruby приложении без HTTP API интерфейса.

2020-07-28 19:40 UTC, BubuntuClu commented on app.rb
> +        [400, headers, ["Unknown time format #{incorrect_params}"]]
сделай метод по отправке сообщений
используй в нем Rack::Response

2020-07-28 19:40 UTC, BubuntuClu commented on app.rb
> +      if incorrect_params.any?
избавься от вложенного ифа

2020-07-28 19:40 UTC, BubuntuClu commented on app.rb
> +  def correct_body(keys)
это тоже все приватные методы. почему только headers в привате?

2020-07-30 06:51 UTC, BubuntuClu requested changes

2020-07-30 06:51 UTC, BubuntuClu commented on time_converter.rb
> +      @success = true
лучше не флаги делать, а метод. сохрани массивы с форматами. сделай метод success? который будет смотреть на unknown_formats

2020-07-30 06:51 UTC, BubuntuClu commented on time_converter.rb
> +  def get_query_params
это приватные методы

2020-07-30 06:51 UTC, BubuntuClu commented on time_converter.rb
> +    keys_for_time = query_params.map do |param|
это по идеи в call делается. в ответе, ты просто формируешь строку из того что насобирал в методе call

2020-07-30 06:51 UTC, BubuntuClu commented on app.rb
> +    response = Rack::Response.new
собирание ответа вынеси в метод и передавай в него текст и код статуса

2020-07-30 13:08 UTC, AntonStashevski commented on app.rb
> +    response = Rack::Response.new
создал метод response(code, message)

2020-07-30 13:12 UTC, AntonStashevski commented on time_converter.rb
> +      @success = true
изменил флаг на success?

2020-07-30 19:05 UTC, BubuntuClu approved these changes

2020-07-30 19:05 UTC, BubuntuClu commented on time_converter.rb
> +    if success?
этот иф тут не нужен. call не возвращает никакие результаты

2020-07-30 19:05 UTC, BubuntuClu commented on app.rb
> +      body = time_formatter.call
call не должен возвращать результат. это просто выполнение действие сервиса.

2020-07-30 19:05 UTC, BubuntuClu commented on time_converter.rb
> +      result(correct_body(query_params))
этот и следующие методы надо вынести в публичные, и вызывать нужный в зависимости от success?

2020-09-12 22:02 UTC, merged